name: stellan
favicon: null
layout_spectrum: 0.5691769411787391
typography_spectrum: 0.6801441530697048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17427917197346687
  lightness: 0.6368607110343874
  saturation: 0.31972601963207126
  rhythmicContrast: 0.3737535187974572
purpose: []
